version: '3'
services:
  api:
    image: jainal09/pp-detection:yolov4-voc
    ports:
      - '5000'
  kafka-consumer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: >
      sh -c "/app/wait-for-it.sh api:80 -- python -u main.py"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - api
